# Generated by Django 4.2 on 2024-12-08 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
