# Generated by Django 4.2 on 2024-12-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake', '0002_subscriber_date_created_subscriber_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
